combatlog:
  tag-duration: 15    # Duration in seconds that players remain in combat after being hit
  ban-duration: 10m   # Duration of the temporary ban (e.g., '10m' for 10 minutes)

messages:
  combat-tagged: "&cYou are now in combat!"
  combat-untagged: "&aYou are no longer in combat!"