combat:
  tag-duration: 15    # Duration in seconds that players remain in combat after being hit
  ban-duration: 10m   # Duration of the temporary ban (e.g., '10m' for 10 minutes)

kill-reward: 10 # Coins rewarded per kill

respawn:
  countdown: 3
  death-title: "&cYOU DIED!"
  death-subtitle: "&eRespawning in %seconds%..."
  respawn-title: "&aReady to fight."
  respawn-subtitle: ""

database:
  # Options: 'mysql' or 'sqlite'
  type: 'sqlite'

  mysql:
    host: 'localhost'
    port: '3306'
    database: 'mythica_kitpvp'
    username: 'root'
    password: 'password'

messages:
  join-message: "&8[&2+&8] &7%player_name% &7has joined the server."
  leave-message: "&8[&4-&8] &7%player_name% &7has left the server."
  combat-tagged: "&cYou are now in combat!"
  combat-untagged: "&aYou are no longer in combat!"