name: MythicaKitPvP
version: '1.0-SNAPSHOT'
main: com.mythicamc.KitPvP
api-version: '1.21'
authors: [ Rhydium ]
description: KitPvP custom built for MythicaMC
website: https://mythicamc.com
softdepend: ["WorldGuard", "WorldEdit", "PlaceholderAPI"]
commands:
  kitpvpbuild:
    description: Toggles build mode for admins.
    usage: /kitpvp build
    permission: kitpvp.admin.build